export default [
  {},
  {
    "id": "1",
    "title": "The North Face",
    "categories": "clothing",
    "subcategories": "coats-jackets",
    "activity": "Outdoors",
    "style": "fit",
    "gender": "male",
    "img_main_url": "/img/products/product_1.jpg",
    "img_gall_url": [
        "/img/products/product_1.jpg",
        "/img/products/product_1.jpg",
        "/img/products/product_1.jpg",
    ],
    "price": "555",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "wishlist": true,
    "cart": false,
  },
      {
    "id": "2",
    "categories": "footwear",
    "title": "Skinners Barefoot Shoes",
    "subcategories": "hiking-shoes",
    "activity": "Outdoors",
  "style": "fit",
    "gender": "male",
    "img_main_url": "/img/products/product_2.jpg",
    "img_gall_url": [
        "/img/products/product_2.jpg",
        "/img/products/product_2.jpg",
        "/img/products/product_2.jpg",
    
    ],
    "price": "75",
    "sizes": [
      "35",
      "37",
      "42",
      "45"
    ],
    "wishlist": false,
    "cart": false,
  },
      {
    "id": "3",
    "categories": "equipment",
    "title": "Joma Backpack",
    "subcategories": "camping-fishing",
    "activity": "Outdoors",
  "style": "fit",
    "gender": "male",
    "img_main_url": "/img/products/product_3.jpg",
    "img_gall_url": [
        "/img/products/product_3.jpg",
        "/img/products/product_3.jpg",
        "/img/products/product_3.jpg",
    ],
    "price": "650",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "wishlist": true,
    "cart": true,
  },
      {
    "id": "4",
    "categories": "bottoms",
    "title": "Kempa Attitude",
    "subcategories": "coats-jackets",
    "activity": "Outdoors",
  "style": "fit",
    "gender": "male",
    "img_main_url": "/img/products/product_4.jpg",
    "img_gall_url": [
        "/img/products/product_4.jpg",
        "/img/products/product_4.jpg",
        "/img/products/product_4.jpg",
    ],
    "price": "999",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "wishlist": false,
    "cart": true,
  },
      {
    "id": "5",
    "categories": "clothing",
    "title": "The North Face  Jacket",
    "subcategories": "coats-jackets",
    "activity": "Outdoors",
  "style": "fit",
    "gender": "female",
    "img_main_url": "/img/products/product_5.jpg",
    "img_gall_url": [
        "/img/products/product_5.jpg",
        "/img/products/product_5.jpg",
        "/img/products/product_5.jpg",
    ],
    "price": "250",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "wishlist": false,
    "cart": false,
  },
      {
    "id": "6",
    "categories": "footwear",
    "title": "Skinners Barefoot Shoes",
    "subcategories": "hiking-shoes",
    "activity": "Outdoors",
  "style": "fit",
    "gender": "male",
    "img_main_url": "/img/products/product_6.jpg",
    "img_gall_url": [
        "/img/products/product_6.jpg",
        "/img/products/product_6.jpg",
        "/img/products/product_6.jpg",
    ],
    "price": "250",
    "sizes": [
      "35",
      "37",
      "42",
      "45"
    ],
    "wishlist": false,
    "cart": true,
  },
      {
    "id": "7",
    "categories": "clothing",
    "title": "The North Face  Jacket",
    "subcategories": "coats-jackets",
    "activity": "Outdoors",
  "style": "fit",
    "gender": "male",
    "img_main_url": "/img/products/product_7.jpg",
    "img_gall_url": [
        "/img/products/product_7.jpg",
        "/img/products/product_7.jpg",
        "/img/products/product_7.jpg",
    ],
    "price": "257",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "wishlist": false,
    "cart": true,
  },
      {
    "id": "8",
    "categories": "clothing",
    "title": "The North Face  Jacket",
    "subcategories": "coats-jackets",
    "activity": "Outdoors",
  "style": "fit",
    "gender": "female",
    "img_main_url": "/img/products/product_8.jpg",
    "img_gall_url": [
        "/img/products/product_8.jpg",
        "/img/products/product_8.jpg",
        "/img/products/product_8.jpg",
    ],
    "price": "250",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "wishlist": false,
    "cart": true,
  },
  {
  "id": "9",
  "title": "The North Face  Jacket",
  "categories": "clothing",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "male",
  "img_main_url": "/img/products/product_1.jpg",
  "img_gall_url": [
      "/img/products/product_1.jpg",
      "/img/products/product_1.jpg",
      "/img/products/product_1.jpg",
  ],
  "price": "555",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
    {
  "id": "10",
  "categories": "footwear",
  "title": "Skinners Barefoot Shoes",
  "subcategories": "hiking-shoes",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "male",
  "img_main_url": "/img/products/product_2.jpg",
  "img_gall_url": [
      "/img/products/product_2.jpg",
      "/img/products/product_2.jpg",
      "/img/products/product_2.jpg",
  
  ],
  "price": "75",
  "sizes": [
    "35",
    "37",
    "42",
    "45"
  ],
  "wishlist": false,
  "cart": false,
},
    {
  "id": "11",
  "categories": "equipment",
  "title": "Joma Backpack",
  "subcategories": "camping-fishing",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "male",
  "img_main_url": "/img/products/product_3.jpg",
  "img_gall_url": [
      "/img/products/product_3.jpg",
      "/img/products/product_3.jpg",
      "/img/products/product_3.jpg",
  ],
  "price": "650",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
    {
  "id": "12",
  "categories": "bottoms",
  "title": "Kempa Attitude",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "male",
  "img_main_url": "/img/products/product_4.jpg",
  "img_gall_url": [
      "/img/products/product_4.jpg",
      "/img/products/product_4.jpg",
      "/img/products/product_4.jpg",
  ],
  "price": "999",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
    {
  "id": "13",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "female",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
    {
  "id": "14",
  "categories": "footwear",
  "title": "Skinners Barefoot Shoes",
  "subcategories": "hiking-shoes",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "male",
  "img_main_url": "/img/products/product_6.jpg",
  "img_gall_url": [
      "/img/products/product_6.jpg",
      "/img/products/product_6.jpg",
      "/img/products/product_6.jpg",
  ],
  "price": "250",
  "sizes": [
    "35",
    "37",
    "42",
    "45"
  ],
  "wishlist": false,
  "cart": false,
},
    {
  "id": "15",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "male",
  "img_main_url": "/img/products/product_7.jpg",
  "img_gall_url": [
      "/img/products/product_7.jpg",
      "/img/products/product_7.jpg",
      "/img/products/product_7.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
    {
  "id": "16",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "female",
  "img_main_url": "/img/products/product_8.jpg",
  "img_gall_url": [
      "/img/products/product_8.jpg",
      "/img/products/product_8.jpg",
      "/img/products/product_8.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
{
  "id": "17",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "female",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
{
  "id": "18",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "female",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
{
  "id": "19",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "female",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
{
  "id": "20",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "female",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
{
  "id": "21",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "female",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
{
  "id": "22",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "male",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
  "look": true,
},
{
  "id": "23",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "male",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
  "look": true,
},
{
  "id": "24",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "style": "fit",
  "gender": "male",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
  "look": true,
},

]