export default [
  {},
  {
    "id": "1",
    "title": "The North Face",
    "categories": "clothing",
    "subcategories": "coats-jackets",
    "activity": "Outdoors",
    "style": "Fit",
    "gender": "male",
    "img_main_url": "/img/products/product_1.jpg",
    "img_gall_url": [
        "/img/products/product_1.jpg",
        "/img/products/product_1.jpg",
        "/img/products/product_1.jpg",
    ],
    "price": "555",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "wishlist": true,
    "cart": false,
  },
      {
    "id": "2",
    "categories": "footwear",
    "title": "Skinners Barefoot Shoes",
    "subcategories": "hiking-shoes",
    "activity": "Outdoors",
    "gender": "male",
    "img_main_url": "/img/products/product_2.jpg",
    "img_gall_url": [
        "/img/products/product_2.jpg",
        "/img/products/product_2.jpg",
        "/img/products/product_2.jpg",
    
    ],
    "price": "75",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "wishlist": false,
    "cart": false,
  },
      {
    "id": "3",
    "categories": "equipment",
    "title": "Joma Backpack",
    "subcategories": "camping-fishing",
    "activity": "Outdoors",
    "gender": "male",
    "img_main_url": "/img/products/product_3.jpg",
    "img_gall_url": [
        "/img/products/product_3.jpg",
        "/img/products/product_3.jpg",
        "/img/products/product_3.jpg",
    ],
    "price": "650",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "wishlist": true,
    "cart": true,
  },
      {
    "id": "4",
    "categories": "bottoms",
    "title": "Kempa Attitude",
    "subcategories": "coats-jackets",
    "activity": "Outdoors",
    "gender": "male",
    "img_main_url": "/img/products/product_4.jpg",
    "img_gall_url": [
        "/img/products/product_4.jpg",
        "/img/products/product_4.jpg",
        "/img/products/product_4.jpg",
    ],
    "price": "999",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "wishlist": false,
    "cart": true,
  },
      {
    "id": "5",
    "categories": "clothing",
    "title": "The North Face  Jacket",
    "subcategories": "coats-jackets",
    "activity": "Outdoors",
    "gender": "female",
    "img_main_url": "/img/products/product_5.jpg",
    "img_gall_url": [
        "/img/products/product_5.jpg",
        "/img/products/product_5.jpg",
        "/img/products/product_5.jpg",
    ],
    "price": "250",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "wishlist": false,
    "cart": false,
  },
      {
    "id": "6",
    "categories": "footwear",
    "title": "Skinners Barefoot Shoes",
    "subcategories": "hiking-shoes",
    "activity": "Outdoors",
    "gender": "male",
    "img_main_url": "/img/products/product_6.jpg",
    "img_gall_url": [
        "/img/products/product_6.jpg",
        "/img/products/product_6.jpg",
        "/img/products/product_6.jpg",
    ],
    "price": "250",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "wishlist": false,
    "cart": true,
  },
      {
    "id": "7",
    "categories": "clothing",
    "title": "The North Face  Jacket",
    "subcategories": "coats-jackets",
    "activity": "Outdoors",
    "gender": "male",
    "img_main_url": "/img/products/product_7.jpg",
    "img_gall_url": [
        "/img/products/product_7.jpg",
        "/img/products/product_7.jpg",
        "/img/products/product_7.jpg",
    ],
    "price": "257",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "wishlist": false,
    "cart": true,
  },
      {
    "id": "8",
    "categories": "clothing",
    "title": "The North Face  Jacket",
    "subcategories": "coats-jackets",
    "activity": "Outdoors",
    "gender": "female",
    "img_main_url": "/img/products/product_8.jpg",
    "img_gall_url": [
        "/img/products/product_8.jpg",
        "/img/products/product_8.jpg",
        "/img/products/product_8.jpg",
    ],
    "price": "250",
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "wishlist": false,
    "cart": true,
  },
  {
  "id": "9",
  "title": "The North Face  Jacket",
  "categories": "clothing",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "style": "Fit",
  "gender": "male",
  "img_main_url": "/img/products/product_1.jpg",
  "img_gall_url": [
      "/img/products/product_1.jpg",
      "/img/products/product_1.jpg",
      "/img/products/product_1.jpg",
  ],
  "price": "555",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
    {
  "id": "10",
  "categories": "footwear",
  "title": "Skinners Barefoot Shoes",
  "subcategories": "hiking-shoes",
  "activity": "Outdoors",
  "gender": "male",
  "img_main_url": "/img/products/product_2.jpg",
  "img_gall_url": [
      "/img/products/product_2.jpg",
      "/img/products/product_2.jpg",
      "/img/products/product_2.jpg",
  
  ],
  "price": "75",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
    {
  "id": "11",
  "categories": "equipment",
  "title": "Joma Backpack",
  "subcategories": "camping-fishing",
  "activity": "Outdoors",
  "gender": "male",
  "img_main_url": "/img/products/product_3.jpg",
  "img_gall_url": [
      "/img/products/product_3.jpg",
      "/img/products/product_3.jpg",
      "/img/products/product_3.jpg",
  ],
  "price": "650",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
    {
  "id": "12",
  "categories": "bottoms",
  "title": "Kempa Attitude",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "gender": "male",
  "img_main_url": "/img/products/product_4.jpg",
  "img_gall_url": [
      "/img/products/product_4.jpg",
      "/img/products/product_4.jpg",
      "/img/products/product_4.jpg",
  ],
  "price": "999",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
    {
  "id": "13",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "gender": "female",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
    {
  "id": "14",
  "categories": "footwear",
  "title": "Skinners Barefoot Shoes",
  "subcategories": "hiking-shoes",
  "activity": "Outdoors",
  "gender": "male",
  "img_main_url": "/img/products/product_6.jpg",
  "img_gall_url": [
      "/img/products/product_6.jpg",
      "/img/products/product_6.jpg",
      "/img/products/product_6.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
    {
  "id": "15",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "gender": "male",
  "img_main_url": "/img/products/product_7.jpg",
  "img_gall_url": [
      "/img/products/product_7.jpg",
      "/img/products/product_7.jpg",
      "/img/products/product_7.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
    {
  "id": "16",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "gender": "female",
  "img_main_url": "/img/products/product_8.jpg",
  "img_gall_url": [
      "/img/products/product_8.jpg",
      "/img/products/product_8.jpg",
      "/img/products/product_8.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
{
  "id": "17",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "gender": "female",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
{
  "id": "18",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "gender": "female",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
{
  "id": "19",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "gender": "female",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
{
  "id": "20",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "gender": "female",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
{
  "id": "21",
  "categories": "clothing",
  "title": "The North Face  Jacket",
  "subcategories": "coats-jackets",
  "activity": "Outdoors",
  "gender": "female",
  "img_main_url": "/img/products/product_5.jpg",
  "img_gall_url": [
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
      "/img/products/product_5.jpg",
  ],
  "price": "250",
  "sizes": [
    "S",
    "M",
    "L",
    "XL"
  ],
  "wishlist": false,
  "cart": false,
},
]



//   { title: "All clothing", url: "/clothing" },
//   { title: "Coats & Jackets", url: "/clothing/coats-jackets" },
//   { title: "T-Shirts & Singlets", url: "/clothing/t-shirts-singlets" },
//   { title: "Tops", url: "/clothing/tops" },
//   { title: "Bottoms", url: "/clothing/bottoms" },
//   { title: "Swimwear", url: "/clothing/swimwear" },
//   { title: "See More...", url: "/clothing" }
// ],
// footwear_links: [
//   { title: "All footwear", url: "/footwear" },
//   { title: "Trekking footwear", url: "/footwear/trekking" },
//   { title: "Hiking shoes", url: "/footwear/hiking-shoes" },
//   { title: "Winter boots", url: "/footwear/winter-boots" },
//   { title: "Multifunctional shoes", url: "/footwear/multifunctional-shoes" },
//   { title: "Leisure shoes", url: "/footwear/leisure-shoes" },
//   { title: "See More...", url: "/footwear" },
// ],
// equipment_links: [
//   { title: "All Equipment", url: "/equipment" },
//   { title: "Camping & Fishing", url: "/equipment/camping-fishing" },
//   { title: "Exercise & Fitness", url: "/equipment/exercise-fitness" },
//   { title: "Swimming & Water Sports", url: "/equipment/swimming-water-sports" },
//   { title: "Hiking & Trekking", url: "/equipment/hiking-trekking" },
//   { title: "See More...", url: "/equipment" },
// ]